#!/bin/bash
set -e
set -x
umask 022
website="$HOME/ekg2"
sandbox="$HOME/tmp/porridge"
pkg="ekg2"
origin="git://github.com/leafnode/${pkg}.git"
tag="$1"
if [ -z "$tag" ]; then
	echo "Usage: $0 <tag>" >&2
	exit 1
fi
if [ "$tag" = "HEAD" ]; then
	date=$(date +%Y%m%d)
	tarball="${pkg}-${date}.tar.bz2"
	dir="${pkg}-${date}"
	dist_target="dist-bzip2"
	checkout_tag="origin/master"
else
	tarball="${tag/_/-}.tar.gz"
	dir="$tag"
	dist_target="dist"
	checkout_tag="$tag"
fi

# Sync repo
cd "$sandbox"
if [ ! -d "$pkg" ]; then
	git clone --bare "$origin"
fi
cd "$pkg"
if ! git remote show origin >/dev/null; then
	git remote add origin "$origin"
fi
git fetch
cd ..

# Checkout, build and install tarball
rm -rf "$dir"
GIT_DIR="$pkg" git archive --prefix="${dir}/" "$checkout_tag" | tar -xf -
cd "$dir"
if [ "$tag" = "HEAD" ]; then
	perl -pi -e "s/^AC\_INIT\(\[ekg2\], \[git\]\)/AC\_INIT\([ekg2], \[${date}\]\)/i" configure.ac
fi
./autogen.sh --build=i386
PATH="$PATH:$HOME/bin" make "$dist_target"
test -f "$tarball"
md5sum "$tarball" > "${tarball}.md5"
chmod a+r "$tarball"{,.md5}
mv -f "$tarball"{,.md5} "${website}/archive/"
cd ..
rm -rf "$dir"

# Update website
cd "$website"
ln -s "archive/$tarball"{,.md5} .
if [ "$tag" != "HEAD" ]; then
	echo Now may be a good idea to sync the website
	crontab -l
fi

