#!/bin/bash
set -e
set -x
umask 022
website="$HOME/ekg2"
sandbox="$HOME/tmp/porridge"
pkg="ekg2"
keep_link_count="6"
origin="git://github.com/leafnode/${pkg}.git"
tag="$1"
if [ -z "$tag" ]; then
	echo "Usage: $0 <tag>" >&2
	exit 1
fi
if [ "$tag" = "HEAD" ]; then
	date=$(date +%Y%m%d)
	ext=".tar.bz2"
	dir="${pkg}-${date}"
	tarball="${dir}${ext}"
	dist_target="dist-bzip2"
	checkout_tag="origin/master"
else
	# Tag is something like ekg2_0.3.1
	ext=".tar.gz"
	dir="$tag"
	tarball="${tag/_/-}${ext}"
	dist_target="dist"
	checkout_tag="$tag"
fi

# Sync repo
cd "$sandbox"
if [ ! -d "$pkg" ]; then
	git clone --bare "$origin"
fi
cd "$pkg"
if ! git remote show origin >/dev/null; then
	git remote add origin "$origin"
fi
git fetch
cd ..

# Checkout, build and install tarball
rm -rf "$dir"
GIT_DIR="$pkg" git archive --prefix="${dir}/" "$checkout_tag" | tar -xf -
cd "$dir"
if [ "$tag" = "HEAD" ]; then
	perl -pi -e "s/^AC\_INIT\(\[ekg2\], \[git\]\)/AC\_INIT\([ekg2], \[${date}\]\)/i" configure.ac
fi
./autogen.sh --build=i386
PATH="$PATH:$HOME/bin" make "$dist_target"
test -f "$tarball"
md5sum "$tarball" > "${tarball}.md5"
chmod a+r "$tarball"{,.md5}
mv -f "$tarball"{,.md5} "${website}/archive/"
cd ..
rm -rf "$dir"

# Update website
cd "$website"
ln -s "archive/$tarball"{,.md5} .
if [ "$tag" = "HEAD" ]; then
	ln -sf "archive/${tarball}"     "ekg2-current${ext}"
	ln -sf "archive/${tarball}.md5" "ekg2-current${ext}.md5"
	# Delete all but $keep_link_count newest snapshot links
	for old_link in $(ls -1 "${pkg}-"[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"${ext}" | sort | head -n "-${keep_link_count}") ; do
		rm -f "${old_link}" "${old_link}.md5"
	done
else
	echo Now may be a good idea to sync the website
	crontab -l
fi

